version: "3.9"

services:
  postgres_db:
    image: $POSTGRES_IMAGE_TAG
    restart: always
    ports:
      - "$DEVICE_POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - DATABASE_HOST=$DATABASE_HOST

  django_web:
    build: .
    command: python manage.py runserver 0.0.0.0:$WEB_INTERNAL_PORT
    volumes:
      - .:/app
    ports:
      - "$WEB_INTERNAL_PORT:$WEB_EXTERNAL_PORT"
    environment:
      - POSTGRES_NAME=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_HOST_SERVICE=$POSTGRES_HOST_SERVICE
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - DEVICE_POSTGRES_PORT=$DEVICE_POSTGRES_PORT
      - DEBUG=$DEBUG
    depends_on:
      - postgres_db